version: "3"

services:
  node:
    image: node:15.7-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./build:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf