version: "3"

services:
  node:
    image: client-node
    container_name: client-node
    build:
      context: .
      dockerfile: ./node/Dockerfile
    tty: true
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
  nginx:
    image: client-nginx
    container_name: client-nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - node