version: "3"

services:
  node:
    image: node:15.7-alpine
    tty: true
    working_dir: /usr/src/app
    command: sh -c "yarn && yarn start"
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./build:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - node