version: "3"

services:
  db:
    image: mysql:latest
    container_name: scheduler_db
    environment:
      MYSQL_ROOT_PASSWORD: ${SCHEDULER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SCHEDULER_MYSQL_DATABASE}
      MYSQL_USER: ${SCHEDULER_MYSQL_USER}
      MYSQL_PASSWORD: ${SCHEDULER_MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/scripts:/scripts
    ports:
      - 3306:3306