version: "3"

services:
  db:
    image: mysql:latest
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${SCHEDULER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SCHEDULER_MYSQL_DATABASE}
      MYSQL_USER: ${SCHEDULER_MYSQL_USER}
      MYSQL_PASSWORD: ${SCHEDULER_MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/scripts:/scripts
    ports:
      - 3306:3306
  proxy:
    image: envoyproxy/envoy:v1.17-latest
    build:
      context: ./proxy
    ports:
      - "8080:8080"