DROP DATABASE IF EXISTS `schedule`;
CREATE DATABASE `schedule`;
USE `schedule`;

DROP TABLE IF EXISTS `schedule`;
CREATE TABLE `schedule` (
  `id` VARCHAR(16) NOT NULL PRIMARY KEY,
  `user_id` VARCHAR(16) NOT NULL,
  `title` VARCHAR(32) NOT NULL,
  `date` DATETIME NOT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME DEFAULT NULL,
  FOREIGN KEY(`user_id`) REFERENCES `user`.`users`(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC;