version: 2.1

executors:
  server:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: circleci/golang:1.14
    environment:
      GO111MODULE: "on"

commands:
  build_and_test_go:
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}
      - run:
          name: Vendoring
          command: go mod download
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - ~/go/pkg/mod/cache
      - run:
          name: Test go package
          command: go test -v ./...

jobs:
  schedule:
    executor:
      name: server
    steps:
      - run: cd ./server/api/schedule
      - build_and_test_go
  client:
    docker:
      - image: circleci/node:12.18.4
    working_directory: ~/client
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn
      - run: yarn test

workflows:
  version: 2
  server:
    jobs:
      - schedule