version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - v1-mod-{{ .Branch }}-{{ checksum "./server/go.mod" }}
      - run:
          name: Vendoring
          command: go mod download
          working_directory: ./server
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "./server/go.mod" }}
          paths:
            - ~/go/pkg/mod/cache
      - run:
          name: Test go package
          command: go test -v ./...
          working_directory: ./server
  client:
    docker:
      - image: circleci/node:12.18.4
    working_directory: ~/client
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn
      - run: yarn test