version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"

jobs:
  schedule:
    executor:
      name: go
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - v1-mod-{{ .Branch }}-{{ checksum "./api/schedule/app/go.mod" }}
      - run:
          name: Vendoring
          working_directory: ./api/schedule/app
          command: go mod download
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "./api/schedule/app/go.mod" }}
          paths:
            - ~/go/pkg/mod/cache
      - run:
          name: Test go package
          working_directory: ./api/schedule/app
          command: go test -v ./...
  client:
    docker:
      - image: circleci/node:12.18.4
    working_directory: ~/client
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - schedule:
          filters:
            branches:
              only: schedule